---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
    requirements-file: molecule/requirements.yml
driver:
  name: delegated
platforms:
  - name: ubuntu-20.04-redis
    server_type: cx11
    image: ubuntu-20.04
lint: |
  /usr/local/bin/flake8
provisioner:
  name: ansible
  env:
    ANSIBLE_FILTER_PLUGINS: ${ANSIBLE_FILTER_PLUGINS:-./plugins/filter}
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY:-./library}
verifier:
  name: testinfra
