---
- include_vars: "{{ var_files }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "vars"
    var_files: "{{ lookup('first_found', params, errors='ignore') }}"
  when: var_files | lenght > 0

- include_tasks: overwrites.yml

- include_tasks: setup.yml
