---
- include_vars: "{{ var_files }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "vars"
    var_files: "{{ lookup('first_found', params, errors='ignore') }}"
  when: var_files

- include_tasks: overwrites.yml

- include_tasks: setup.yml
